# Generated by Django 4.0.4 on 2022-10-20 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techpoints', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='order_id',
            new_name='product_id',
        ),
    ]
