# Generated by Django 4.0.4 on 2022-10-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpoints', '0003_transaction_date_transaction_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='roll_number',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='roll_number',
        ),
        migrations.AddField(
            model_name='transaction',
            name='remarks',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
