# Generated by Django 4.0.4 on 2022-10-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpoints', '0004_remove_order_roll_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='event_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='points_earned',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
