# Generated by Django 4.0.4 on 2022-10-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpoints', '0006_alter_order_order_id_alter_order_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='total_points',
            field=models.IntegerField(),
        ),
    ]
