# Generated by Django 4.0.4 on 2022-10-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpoints', '0007_alter_student_total_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
