# Generated by Django 4.1.1 on 2022-10-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpoints', '0009_order_deliver_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_desc',
            field=models.TextField(default='Description'),
        ),
    ]
