# Generated by Django 4.0.4 on 2022-10-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techpoints', '0011_alter_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_change_time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tentative_delivery',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
